config/routes.rb
Rails.application.routes.draw do

  get 'statuses/show'

  get 'statuses/edit'

  root 'pages#home'
  get '/actualize-corporate-training' => 'pages#corporate_training'
  get '/chicago-coding-bootcamp' => 'pages#in_person'
  get '/online-coding-bootcamp' => 'pages#online'
  get '/hiring' => 'pages#hiring'
  post '/hiring' => 'pages#send_to_hiring'
  get '/in-person', to: redirect('/chicago-coding-bootcamp')
  get '/online', to: redirect('/online-coding-bootcamp')
  get '/financing' => 'pages#financing'
  get '/ruby' => 'pages#repl'
  get '/javascript' => 'pages#javascript_repl'

  get '/newsletter/think-like-a-software-engineer' => 'pages#tlase'
  get '/newsletter/learn-to-code-in-60-days' => 'pages#sixty_day'

  devise_for :admins, :controllers => { registrations: 'registrations' }
  get 'admins/dashboard' => 'admins#dashboard'

  scope format: false do
    get '/*date/*title', to: 'blog_posts#show', date: %r[\d{4}/\d{2}/\d{2}], as: 'post'
  end

  get '/sitemap.xml', :to => 'sitemaps#index', :defaults => {:format => 'xml'}

  get '/pages/thank_you'
  get '/coding_foundations/thank_you' => "open_prework#thank_you"
  get '/pages/webinar_thank_you'
  get '/pages/tlase_thank_you'
  get '/pages/contacts_thank_you', :as => :contacts_thank_you
  get "/tours/thank_you" => "tours#thank_you", :as => :tours_thank_you
  get "/pages/tours/thank_you" => "pages#tour_thank_you", :as => :pages_tours_thank_you
  get '/pages/scholarship_thank_you'
  get '/corporate_training' => 'corporate_training_messages#corporate_training', :as => :corporate_training
  get '/corporate_training_thank_you' => 'corporate_training_messages#thank_you', :as => :corporate_training_thank_you

  get '/privacy_policy' => 'pages#privacy_policy'

  get "/apply" => "subscribers#apply", :as => :new_application #new_application_path has been altered for split test
  get "/applications/new/:id" => "applications#new"

  get "/subscribers/download"
  get "/subscribers/career_pdf_download"

  post 'subscribers_application' => 'subscribers#create_from_started_application'
  post 'subscribers_curriculum' => 'subscribers#create_from_curriculum'
  post 'subscribers_teaching_book' => 'subscribers#create_from_teaching_book'
  post 'subscribers_tutorial' => 'subscribers#create_from_tutorial'
  post 'subscribers_footer' => 'subscribers#create_from_footer'
  post 'subscribers_webinar' => 'subscribers#create_from_webinar'
  post 'subscribers_tlase' => 'subscribers#create_from_tlase'
  post 'subscribers_sixty_day' => 'subscribers#create_from_sixty_day'
  post 'subscribers_blog' => 'subscribers#create_from_blog'
  post 'subscribers_career_pdf' => 'subscribers#create_from_career_pdf'
  post 'subscribers_tour' => 'subscribers#create_from_tour'
  post 'subscribers' => 'subscribers#create_from_tour'
  post 'subscribers_popup' => 'subscribers#create_from_popup'

  resources :blog_posts
  resources :blog_categories
  resources :applications
  resources :scholarships, only: [:new, :create]
  resources :lakewood_applications
  resources :statuses, only: [:edit, :update]
  resources :faqs
  resources :contacts
  resources :mini_courses
  resources :mini_course_applications
  resources :subscribers, :only => [:index]
  resources :capstones, only: [:index]
  resources :screencasts, only: [:index]
  resources :interviews
  resources :corporate_training_messages, only: [:index, :new, :create, :show]
  resources :tours
  resources :info_session_sign_ups
  resources :info_sessions

  get "/careers" => "job_openings#index", as: :careers

  get "/options/" => "interviews#interview_options"

  get "/videos/think-like-a-software-engineer" => 'videos#tlase_show'
  get "/videos/learn-to-code-in-60-days" => 'videos#sixty_day_show'

  get "/think-like-a-software-engineer/videos" => 'videos#tlase_index'
  post "/think-like-a-software-engineer/videos" => 'videos#tlase_create'
  get "/think-like-a-software-engineer/videos/new" => 'videos#tlase_new'
  get "/think-like-a-software-engineer/videos/:episode_id/edit" => 'videos#tlase_edit'
  patch "/think-like-a-software-engineer/videos/:episode_id" => 'videos#tlase_update'
  get "/think-like-a-software-engineer/videos/:episode_id" => 'videos#new_tlase_show'

  get "/tutorial/lessons" => "lessons#index"
  get "/tutorial/lessons/:title" => "lessons#show"

  get "/tutorial_submissions" => "tutorial_submissions#index"
  post "/tutorial_submissions" => "tutorial_submissions#create"
  patch "/tutorial_submissions/ajax" => "tutorial_submissions#ajax_update"

  get "/profiles" => "profiles#index"
  patch "/profiles/:id" => "profiles#update"
  post "/profiles" => "profiles#create"
  get "/profiles/:id" => "profiles#modal"

  get "/lakewood_profiles" => "lakewood_profiles#index"
  patch "/lakewood_profiles/:id" => "lakewood_profiles#update"
  post "/lakewood_profiles" => "lakewood_profiles#create"
  get "/lakewood_profiles/:id" => "lakewood_profiles#modal"

  get "/referrals" => "referrals#index", :as => :referrals
  get "/referrals/new" => "referrals#new", :as => :new_referral
  post "/referrals" => "referrals#create"
  get "/referrals/thank_you" => "referrals#thank_you"

  get "/coding-bootcamps/community-info" => "pages#communities_index"
  get "/coding-bootcamps/:location/community-info" => "pages#communities"
  get "/codecademy" => "pages#codecademy"
  get "/resources" => "pages#resources"

  get "/codenewbie" => 'pages#codenewbie'
  get "/code-newbie" => 'pages#codenewbie'
  get "/codenewbies" => 'pages#codenewbie'

  post "/social-media" => 'social_media#new_post'

  get "/coding-foundations" => "open_prework#index"
  get "/enroll/coding-foundations" => "open_prework#enroll_form"
  get "/coding-foundations/terms-of-service" => "open_prework#terms_of_service"
  post "/enroll/coding-foundations" => "open_prework#enroll"
  get "/coding-foundations/thank-you" => "open_prework#thank_you"
  get "/enroll/email" => "open_prework#email"

  get "/josh/appreciation/new" => "pages#josh_new"
  post "/josh/appreciation" => "pages#josh_create"
  get "/josh/appreciation" => "pages#josh_index"

end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_filter :authenticate_admin!, only: [:new, :create, :update, :delete]

  def index
    redirect_to "/"
  end

  def new
    @faq = Faq.new
  end

  def create
    @faq = Faq.new(faq_params)
    if @faq.save
      flash[:success] = "FAQ has been added"
      redirect_to faqs_path
    else
      render :new
    end
  end

  def edit
    @faq = Faq.find(params[:id])
  end

  def update
    @faq = Faq.find(params[:id])
    @faq.update(faq_params)
    if @faq.save
      flash[:success] = "FAQ has been updated"
      redirect_to faqs_path
    else
      render :update
    end
  end

  def destroy
    Faq.find(params[:id]).destroy
    flash[:warning] = "FAQ has been deleted"
    redirect_to faqs_path
  end

  private

  def faq_params
    params.require(:faq).permit(:question, :answer, :priority, :category)
  end

end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
<%= form_for @faq do |f| %>
  <div class="form-group">
    <%= f.label :question %><br />
    <%= f.text_field :question, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :answer %><br />
    <%= f.text_area :answer, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :priority %><br />
    <%= f.text_field :priority, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %><br />
    <%= f.select :category, options_for_select(["General", "Tuition & Payment", "Application & Acceptance", "Actualize Program", "Etc."], @faq.category), {:include_blank => '-Select-'}, { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.submit submit_button, class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<%= render "/layouts/page_title", page_title: "FAQ", page_subtitle: "Frequently Asked Questions" %>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
  <h2>Edit FAQ</h2>
    <%= render "form",  submit_button: "Edit FAQ" %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/faqs/index.html.erb
<%= render "/layouts/page_title", page_title: "FAQ", page_subtitle: "Frequently Asked Questions" %>
<% content_for :head do %>
  <title> Frequently Asked Questions about ACLTC and Actualize </title>
    <meta name="description" content='Learn more about Anyone Can Learn To Code & Actualize coding school scheduling, tuition & payments, curriculum, teaching style, & more.'>
  <% end %>
  

        <!-- Content
        ============================================= -->
        <section id="content">

          <div class="content-wrap">

            <div class="container clearfix">

                    <!-- Post Content
                    ============================================= -->


                      <div class="clear"></div>
                      <ul id="blog_admin_list">
                        <li><%= link_to('Create FAQ', new_faq_path) if current_admin %></li>
                      </ul>
                      <div id="faqs" class="faqs">
         
                        <% @faq_categories.each do |category| %>
                          <div><h3 class="faq-header" style="padding-bottom:15px;"><%= category.upcase %></h3></div>
                          <% @faqs.each do |faq| %>
                            <% if faq.category == category %>             
                              <div class="toggle faq faq-marketplace faq-authors">
                                <div class="togglet"><i class="toggle-closed fa fa-plus"></i><i class="toggle-open fa fa-minus"></i><p class=" toggle-open faq-text"><%= faq.question %></p></div>
                                <div class="togglec">
                                  <%= faq.answer.html_safe %>
                                  <%= link_to "| Edit", edit_faq_path(faq) if current_admin %>
                                  <%= link_to "| Delete", faq_path(faq), method: :delete, data: {:confirm => 'Are you sure?'} if current_admin %>
                                </div>
                              </div>
                            <% end %>
                          <% end %>
                          <br>
                        <% end %>
                      
                      </div>


                    <script type="text/javascript">
                      jQuery(document).ready(function($){
                        var $faqItems = $('#faqs .faq');
                        if( window.location.hash != '' ) {
                          var getFaqFilterHash = window.location.hash;
                          var hashFaqFilter = getFaqFilterHash.split('#');
                          if( $faqItems.hasClass( hashFaqFilter[1] ) ) {
                            $('#portfolio-filter li').removeClass('activeFilter');
                            $( '[data-filter=".'+ hashFaqFilter[1] +'"]' ).parent('li').addClass('activeFilter');
                            var hashFaqSelector = '.' + hashFaqFilter[1];
                            $faqItems.css('display', 'none');
                            if( hashFaqSelector != 'all' ) {
                              $( hashFaqSelector ).fadeIn(500);
                            } else {
                              $faqItems.fadeIn(500);   
                            }
                          }                                    
                        }

                        $('#portfolio-filter a').click(function(){
                          $('#portfolio-filter li').removeClass('activeFilter');
                          $(this).parent('li').addClass('activeFilter');
                          var faqSelector = $(this).attr('data-filter');
                          $faqItems.css('display', 'none');
                          if( faqSelector != 'all' ) {
                            $( faqSelector ).fadeIn(500);
                          } else {
                            $faqItems.fadeIn(500);
                          }
                          return false;
                        });
                      });
                    </script>
            </section><!-- #content end -->

app/views/faqs/new.html.erb
<%= render "/layouts/page_title", page_title: "FAQ", page_subtitle: "Frequently Asked Questions" %>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
  <h2>Create FAQ</h2>
    <%= render "form", submit_button: "Create FAQ" %>
  </div>
  <div class="col-md-2"></div>
</div>