config/routes.rb
Rails.application.routes.draw do

  get 'statuses/show'

  get 'statuses/edit'

  root 'pages#home'
  get '/actualize-corporate-training' => 'pages#corporate_training'
  get '/chicago-coding-bootcamp' => 'pages#in_person'
  get '/online-coding-bootcamp' => 'pages#online'
  get '/hiring' => 'pages#hiring'
  post '/hiring' => 'pages#send_to_hiring'
  get '/in-person', to: redirect('/chicago-coding-bootcamp')
  get '/online', to: redirect('/online-coding-bootcamp')
  get '/financing' => 'pages#financing'
  get '/ruby' => 'pages#repl'
  get '/javascript' => 'pages#javascript_repl'

  get '/newsletter/think-like-a-software-engineer' => 'pages#tlase'
  get '/newsletter/learn-to-code-in-60-days' => 'pages#sixty_day'

  devise_for :admins, :controllers => { registrations: 'registrations' }
  get 'admins/dashboard' => 'admins#dashboard'

  scope format: false do
    get '/*date/*title', to: 'blog_posts#show', date: %r[\d{4}/\d{2}/\d{2}], as: 'post'
  end

  get '/sitemap.xml', :to => 'sitemaps#index', :defaults => {:format => 'xml'}

  get '/pages/thank_you'
  get '/coding_foundations/thank_you' => "open_prework#thank_you"
  get '/pages/webinar_thank_you'
  get '/pages/tlase_thank_you'
  get '/pages/contacts_thank_you', :as => :contacts_thank_you
  get "/tours/thank_you" => "tours#thank_you", :as => :tours_thank_you
  get "/pages/tours/thank_you" => "pages#tour_thank_you", :as => :pages_tours_thank_you
  get '/pages/scholarship_thank_you'
  get '/corporate_training' => 'corporate_training_messages#corporate_training', :as => :corporate_training
  get '/corporate_training_thank_you' => 'corporate_training_messages#thank_you', :as => :corporate_training_thank_you

  get '/privacy_policy' => 'pages#privacy_policy'

  get "/apply" => "subscribers#apply", :as => :new_application #new_application_path has been altered for split test
  get "/applications/new/:id" => "applications#new"

  get "/subscribers/download"
  get "/subscribers/career_pdf_download"

  post 'subscribers_application' => 'subscribers#create_from_started_application'
  post 'subscribers_curriculum' => 'subscribers#create_from_curriculum'
  post 'subscribers_teaching_book' => 'subscribers#create_from_teaching_book'
  post 'subscribers_tutorial' => 'subscribers#create_from_tutorial'
  post 'subscribers_footer' => 'subscribers#create_from_footer'
  post 'subscribers_webinar' => 'subscribers#create_from_webinar'
  post 'subscribers_tlase' => 'subscribers#create_from_tlase'
  post 'subscribers_sixty_day' => 'subscribers#create_from_sixty_day'
  post 'subscribers_blog' => 'subscribers#create_from_blog'
  post 'subscribers_career_pdf' => 'subscribers#create_from_career_pdf'
  post 'subscribers_tour' => 'subscribers#create_from_tour'
  post 'subscribers' => 'subscribers#create_from_tour'
  post 'subscribers_popup' => 'subscribers#create_from_popup'

  resources :blog_posts
  resources :blog_categories
  resources :applications
  resources :scholarships, only: [:new, :create]
  resources :lakewood_applications
  resources :statuses, only: [:edit, :update]
  resources :faqs
  resources :contacts
  resources :mini_courses
  resources :mini_course_applications
  resources :subscribers, :only => [:index]
  resources :capstones, only: [:index]
  resources :screencasts, only: [:index]
  resources :interviews
  resources :corporate_training_messages, only: [:index, :new, :create, :show]
  resources :tours
  resources :info_session_sign_ups
  resources :info_sessions

  get "/careers" => "job_openings#index", as: :careers

  get "/options/" => "interviews#interview_options"

  get "/videos/think-like-a-software-engineer" => 'videos#tlase_show'
  get "/videos/learn-to-code-in-60-days" => 'videos#sixty_day_show'

  get "/think-like-a-software-engineer/videos" => 'videos#tlase_index'
  post "/think-like-a-software-engineer/videos" => 'videos#tlase_create'
  get "/think-like-a-software-engineer/videos/new" => 'videos#tlase_new'
  get "/think-like-a-software-engineer/videos/:episode_id/edit" => 'videos#tlase_edit'
  patch "/think-like-a-software-engineer/videos/:episode_id" => 'videos#tlase_update'
  get "/think-like-a-software-engineer/videos/:episode_id" => 'videos#new_tlase_show'

  get "/tutorial/lessons" => "lessons#index"
  get "/tutorial/lessons/:title" => "lessons#show"

  get "/tutorial_submissions" => "tutorial_submissions#index"
  post "/tutorial_submissions" => "tutorial_submissions#create"
  patch "/tutorial_submissions/ajax" => "tutorial_submissions#ajax_update"

  get "/profiles" => "profiles#index"
  patch "/profiles/:id" => "profiles#update"
  post "/profiles" => "profiles#create"
  get "/profiles/:id" => "profiles#modal"

  get "/lakewood_profiles" => "lakewood_profiles#index"
  patch "/lakewood_profiles/:id" => "lakewood_profiles#update"
  post "/lakewood_profiles" => "lakewood_profiles#create"
  get "/lakewood_profiles/:id" => "lakewood_profiles#modal"

  get "/referrals" => "referrals#index", :as => :referrals
  get "/referrals/new" => "referrals#new", :as => :new_referral
  post "/referrals" => "referrals#create"
  get "/referrals/thank_you" => "referrals#thank_you"

  get "/coding-bootcamps/community-info" => "pages#communities_index"
  get "/coding-bootcamps/:location/community-info" => "pages#communities"
  get "/codecademy" => "pages#codecademy"
  get "/resources" => "pages#resources"

  get "/codenewbie" => 'pages#codenewbie'
  get "/code-newbie" => 'pages#codenewbie'
  get "/codenewbies" => 'pages#codenewbie'

  post "/social-media" => 'social_media#new_post'

  get "/coding-foundations" => "open_prework#index"
  get "/enroll/coding-foundations" => "open_prework#enroll_form"
  get "/coding-foundations/terms-of-service" => "open_prework#terms_of_service"
  post "/enroll/coding-foundations" => "open_prework#enroll"
  get "/coding-foundations/thank-you" => "open_prework#thank_you"
  get "/enroll/email" => "open_prework#email"

  get "/josh/appreciation/new" => "pages#josh_new"
  post "/josh/appreciation" => "pages#josh_create"
  get "/josh/appreciation" => "pages#josh_index"

end

app/models/application.rb
class Application < ActiveRecord::Base

   validates :first_name, :last_name, :email, :phone, :address, :learn_about_acltc, :location, :primary_goals, :programming_experience, :current_occupation, :preferred_work_location, :work_concurrently, :why_better, :tinker_example, :time_to_reach, presence: true, on: :create

  has_many :statuses
  has_one :profile

  def full_name
    "#{first_name} #{last_name}"
  end

  def applications_human_time
    updated_at.strftime("%A, %d %b %Y %l:%M %p")
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |application|
        csv << application.attributes.values_at(*column_names)
      end
    end
  end

  def self.remind(first_name, email, phone)
    AcltcMailer.complete_your_application_reminder(first_name, email, phone).deliver unless Application.find_by(email: email)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def after_sign_in_path_for(resource)
    admins_dashboard_path(current_admin)
  end

  def track_web_traffic_source
    cookies[:source] = "#{params[:utm_source]} #{params[:utm_medium]}" if params[:utm_medium]
    cookies[:source] = request.referer unless cookies[:source]
  end

  def create_new_lead
    cookies[:subscriber] = params[:email]
    @subscriber = Subscriber.new(email: params[:email], first_name: params[:first_name], phone: params[:phone], mousetrap: params[:mousetrap], ip_address: request.remote_ip, source: cookies[:source])

    lead = Unirest.post("https://actualize-crm.herokuapp.com/api/v1/leads.json", headers: {
    "Accept" => "application/json", "Content-Type" => "application/json"},
     parameters: {:first_name => params[:first_name], :email => params[:email], :phone => params[:phone], :name => params[:mousetrap], :ip => @subscriber.ip_address, :source => cookies[:source]}).body
  end

  def record_return_to_website_event
    if cookies[:subscriber] && hasnt_visited_within_24_hours
      lead = Unirest.post("https://actualize-crm.herokuapp.com/api/v1/leads.json", headers: {
      "Accept" => "application/json", "Content-Type" => "application/json"},
       parameters: {:email => cookies[:subscriber], :name => "Visited Website"}).body
      cookies[:last_visited] = Time.now
    end
  end

  private

  def hasnt_visited_within_24_hours
    !cookies[:last_visited] || (Time.now - DateTime.parse(cookies[:last_visited])) > 86400
  end

  def verify_subscriber
    unless cookies[:is_subscriber] || cookies[:subscriber]
      redirect_to tutorial_lessons_path
    end
  end

  def authenticate_corporate_training_access
    if current_admin && current_admin.email == "jay@anyonecanlearntocode.com"
      @corporate_access = Admin.find_by(email: "jay@anyonecanlearntocode.com")
    elsif current_admin && current_admin.email == "zev@anyonecanlearntocode.com"
      @corporate_access = Admin.find_by(email: "zev@anyonecanlearntocode.com")
    # elsif current_admin && current_admin.email == "test@gmail.com"
    #   @corporate_access = Admin.find_by(email: "test@gmail.com")
    else
      redirect_to admins_dashboard_path
      flash[:warning] = "You do not have access to this page"
    end
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :authenticate_admin!, except: [:new, :create]
  include CohortDatesHelper
  invisible_captcha only: [:create], honeypot: :subtitle

  def index
    @applications = Application.all
    @tours = Tour.all

    if params[:location_filter]
      @applications = Application.where(location: params[:location_filter])
    end

    @applications = Application.order(params[:sort]) if params[:sort]
    @applications = Application.where(status: params[:status]) if params[:status]

    respond_to do |format|
      format.html
      format.csv { send_data @applications.to_csv }
    end
  end

  def show
    @application = Application.find(params[:id])

    cohort_dates = cohort_start_dates
    @dates_by_city = []

    cohort_start_dates.each do |cohort_date|
      if cohort_date[:prework] && Time.zone.now <= cohort_date[:live] + 1.month
        @dates_by_city << ["#{cohort_date[:location]} #{cohort_date[:live].strftime('%m/%d/%y')}"]
      end
    end
  end

  def edit
    @application = Application.find(params[:id])
  end

  def new
    if params[:application_type] == "scholarship"
      redirect_to '/pages/scholarship_thank_you'
    else
      if params[:referral] == "wwcode"
        @scholarship = "wwcode"
      end
      @application = Application.new
    end
    render layout: 'main'
  end

  def create
    @application = Application.new(application_params)
    if @application.save
      create_new_lead
      AcltcMailer.application_email(@application).deliver_now
      AcltcMailer.application_email_reply(@application).deliver_now
      redirect_to "/pages/thank_you"
    else
      render 'new', layout: 'main'
    end
  end

  def update
    @application = Application.find(params[:id])
    status_changed = true unless @application.status == params[:application][:status]

    if @application.update(application_params)
      if status_changed
        @application.statuses.create(text: params[:application][:status], date: Date.today)
      end
      flash[:info] = "Application status updated!"
      redirect_to @application
    else
      flash[:danger] = "Something went wrong!"
      redirect_to @application
    end
  end

  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    flash[:danger] = "Application successfully deleted!"
    redirect_to "/applications"
  end

  private

  def application_params
    params.require(:application).permit(:first_name, :last_name, :email, :phone, :address,
    :emergency_contact, :learn_about_acltc, :learn_about_acltc_specify, :current_occupation,
    :primary_goals, :programming_experience, :preferred_work_location,
    :work_concurrently, :tinker_example, :why_better, :status, :location, :cohort,
    :notes, :long, :time_to_reach)
  end

  def create_hubspot_contact
    begin
      lower_levels = ["Mousetrap", "Info Session", "Tour"]
      contact = Hubspot::Contact.find_by_email(application_params[:email])
      if contact
        if lower_levels.include?(contact["lead_type"])
          contact.update!({lead_type: "Complete Application"})
        end
      else
        Hubspot::Contact.create!(application_params[:email], {firstname: application_params[:first_name], lastname: application_params[:last_name], phone: application_params[:phone], lead_type: "Complete Application", created_at: @application.created_at })
      end
    rescue Exception => e
      p "rescue #{e.message}"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/index.html.erb
<%= render "/layouts/page_title", page_title: "Applications", page_subtitle: "" %>
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

<div class="chart">
  <h4>Total Applications Per Month</h4>
  <%= line_chart Application.group_by_month(:created_at, format: "%b %Y", last: 20).count, colors: ["#18A497"], discrete: true, xtitle: "Month", ytitle: "Number of Applications" %>
</div>
<div class="chart">
  <h4>Applications Per Month by Location</h4>
  <%= line_chart Application.group(:location).group_by_month(:created_at, format: "%b %Y", last: 20).count, discrete: true, xtitle: "Month", ytitle: "Number of Applications" %>
</div>
<div class="chart">
  <h4>How Applicants Learned About ACLTC</h4>
  <%= pie_chart Application.group(:learn_about_acltc).where.not(:learn_about_acltc => nil).count %>
</div>
<div class="chart">
  <h4>Students Registered per Cohort</h4>
  <%= column_chart Application.group(:cohort).where(:status => 'Paid Deposit').where.not(:cohort => 'CHI 4/16').count %>
</div>

<div class="chart">
  <h4>Every Applicant's Status</h4>
  <%= pie_chart Application.group(:status).where.not(:status => nil).count %>
</div>

<div class="chart">
  <h4>Total Tours Per Month</h4>
  <%= line_chart Tour.group_by_month(:created_at, format: "%b %Y", last: 20).count, colors: ["#18A497"], discrete: true, xtitle: "Month", ytitle: "Number of Tours" %>
</div>
<div class="chart">
  <h4>Tours Per Month by Location</h4>
  <%= line_chart Tour.group(:city).group_by_month(:created_at, format: "%b %Y", last: 20).count, discrete: true, xtitle: "Month", ytitle: "Number of Tours" %>
</div>

<section id="content">
  <div class="content-wrap dash-wrap">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <%= link_to "Download Applications CSV", applications_path(format: "csv"), :class => 'button btn-secondary csv-button'  %>

        <table class="table table-striped index-dash-table">
          <tr>
          <th>Name</th>
            <th>Submitted On</th>
            <th>
              <div class="dropdown">
                <a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="color:gray;">
                  Location
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  <li><a href="/applications?location_filter=Chicago">Chicago</a></li>
                  <li><a href="/applications?location_filter=New York City">New York City</a></li>
                  <li><a href="/applications?location_filter=San Francisco">San Francisco</a></li>
                  <li><a href="/applications">All</a></li>
                </ul>
              </div>
            </th>
            <th>Status</th>
            <th>Cohort</th>
            <th>View Profile</th>
          </tr>
          <% @applications.order("created_at desc").each do |application| %>
          <tr>
            <td><%= link_to application.full_name, application_path(application) %></td>
            <td><%= application.created_at.strftime("%A %B %d, %Y") %></td>
            <td><%= application.location %></td>
            <td><a href="/applications?status=<%= application.status %>"><%= application.status %></a></td>
            <td><%= application.cohort %></td>
            <td>
              <%= link_to 'Profile', "/profiles/#{application.id}",  {:remote => true, 'data-target' => '#profile-modal'}  %>
            </td>
          </tr>
          <% end %>
        </table>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</section>

<script type="text/javascript">
  $('.dropdown-toggle').dropdown();
</script>

app/views/applications/show.html.erb
<%= render "/layouts/page_title", page_title: "Applications", page_subtitle: "" %>
<section id="content">
  <div class="content-wrap dash-wrap">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="application-links">
          <%= link_to "Back to Index", applications_path, class: "btn btn-success left-link" %>
          <%= link_to "Profile", "/profiles/#{@application.id}", {:remote => true, 'data-target' => '#profile-modal', class: "btn btn-default left-link" } %>
          <%= link_to 'Delete', application_path(@application), method: :delete, data: { confirm: 'Are you sure you want to delete this application?' }, class: "btn btn-danger right-link" %>
        </div>
        <div class="status-cohort">
          <%= form_for @application, :html => {:class => 'status-cohort-form'} do |f| %>
            <%= f.select(:status, options_for_select([['Initial Call Scheduled'], ['Missed Call'], ['Interview 1 Scheduled'], ['Had Interview 1'], ['Missed Interview 1'], ['Interview 2 Scheduled'], ['Had Interview 2'], ['Missed Interview 2'], ['Applicant Undecided'], ['Rejected'], ['Accepted'], ['Submitted Enrollment Agreement'], ['Paid Deposit'], ['Deferred'], ['Declined (Financial)'], ['Declined (Schedule)'], ['Declined (Competitor)'], ['Declined (Location)'], ['Declined (Other)'], ['Interview Never Scheduled']], @application.status), {:include_blank => 'Select Status'}, { class: 'form-control' })%>
            <%= f.select(:cohort, options_for_select(@dates_by_city, @application.cohort), {:include_blank => 'Select Cohort'}, { class: 'form-control' })%>
            <%= f.label :notes, class: "sr-only" %>
            <%= f.text_field :notes, placeholder: "Add a note", class: "form-control" %>
            <%= f.submit "Update", class: "btn btn-primary select-button"%>
          <% end %>
        </div>
        <table class="table table-striped">
          <tr>
            <th>Application Sent:</th>
            <td class="col-md-5"><%= @application.created_at.strftime("%A %B %d, %Y") %></td>
          </tr>
          <tr>
            <th class="col-md-3">Notes:</th>
            <td class="col-md-5"><%= @application.notes %></td>
          </tr>
          <tr>
            <th class="col-md-3">Cohort:</th>
            <td class="col-md-5"><%= @application.cohort %></td>
          </tr>
          <tr>
            <th class="col-md-3">Status:</th>
            <td class="col-md-5"><%= @application.status %></td>
          </tr>
          <tr>
            <th class="col-md-3">History:</th>
            <td class="col-md-5">
              <% @application.statuses.each do |status| %>
                <div><%= link_to("#{status.text} #{status.date}", edit_status_path(status)) %></div>
              <% end %>
            </td>
          </tr>
          <tr>
            <th class="col-md-3">First Name:</th>
            <td class="col-md-5"><%= @application.first_name %></td>
          </tr>
          <tr>
            <th class="col-md-3">Last Name:</th>
            <td class="col-md-5"><%= @application.last_name %></td>
          </tr>
          <tr>
            <th>Email:</th>
            <td class="col-md-5"><%= @application.email %></td>
          </tr>
          <tr>
            <th>Phone:</th>
            <td class="col-md-5"><%= @application.phone %></td>
          </tr>
          <tr>
            <th>Address:</th>
            <td class="col-md-5"><%= @application.address %></td>
          </tr>
          <tr>
            <th>Emergency Contact:</th>
            <td class="col-md-5"><%= @application.emergency_contact %></td>
          </tr>
          <tr>
            <th>Location:</th>
            <td class="col-md-5"><%= @application.location %></td>
          </tr>
          <tr>
            <th>How they heard about Actualize:</th>
            <td class="col-md-5"><%= @application.learn_about_acltc %></td>
          </tr>
          <tr>
            <th>If "Other," how they heard about Actualize:</th>
            <td class="col-md-5"><%= @application.learn_about_acltc_specify %></td>
          </tr>
          <tr>
            <th>Their primary goals in learning how to code?:</th>
            <td class="col-md-5"><%= @application.primary_goals %></td>
          </tr>
          <tr>
            <th>Previous programming experience:</th>
            <td class="col-md-5"><%= @application.programming_experience %></td>
          </tr>
          <tr>
            <th>What they're currently doing (job or school, etc.):</th>
            <td class="col-md-5"><%= @application.current_occupation %></td>
          </tr>
          <tr>
            <th>City where they will search for web development jobs:</th>
            <td class="col-md-5"><%= @application.preferred_work_location %></td>
          </tr>
          <tr>
            <th>How they will manage a job and the bootcamp, if applicable:</th>
            <td class="col-md-5"><%= @application.work_concurrently %></td>
          </tr>
          <tr>
            <th>Why they should be accepted over well-qualified candidates?:</th>
            <td class="col-md-5"><%= @application.why_better %></td>
          </tr>
          <tr>
            <th>Examples of complex problem solving and logical analysis:</th>
            <td class="col-md-5"><%= @application.tinker_example %></td>
          </tr>
          <tr>
            <th>Google Hangouts Email:</th>
            <td class="col-md-5"><%= @application.hangouts_email %></td>
          </tr>
          <tr>
            <th>Scholarship applicant:</th>
            <td class="col-md-5"><%= @application.scholarship_applicant %></td>
          </tr>
          <tr>
            <th>Best Time To Reach:</th>
            <td class="col-md-5"><%= @application.time_to_reach %></td>
          </tr>
          <% if @application.scholarship_applicant %>
            <tr>
              <th class="diversity-scholarship">How they heard about Diversity Scholarship:</th>
              <td class="col-md-5"><%= @application.learn_about_scholarship %></td>
            </tr>
            <tr>
              <th class="diversity-scholarship">Identifies as a woman or as gendeir-diverse:</th>
              <td class="col-md-5"><%= @application.woman %></td>
            </tr>
            <tr>
              <th class="diversity-scholarship">Belongs to a racial group that is underrepresented in tech:</th>
              <td class="col-md-5"><%= @application.minority %></td>
            </tr>
            <tr>
              <th class="diversity-scholarship">Why they should be awarded scholarship over other applicants:</th>
              <td class="col-md-5"><%= @application.why_scholarship %></td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</section>