config/routes.rb
Rails.application.routes.draw do

  get 'statuses/show'

  get 'statuses/edit'

  root 'pages#home'
  get '/actualize-corporate-training' => 'pages#corporate_training'
  get '/chicago-coding-bootcamp' => 'pages#in_person'
  get '/online-coding-bootcamp' => 'pages#online'
  get '/hiring' => 'pages#hiring'
  post '/hiring' => 'pages#send_to_hiring'
  get '/in-person', to: redirect('/chicago-coding-bootcamp')
  get '/online', to: redirect('/online-coding-bootcamp')
  get '/financing' => 'pages#financing'
  get '/ruby' => 'pages#repl'
  get '/javascript' => 'pages#javascript_repl'

  get '/newsletter/think-like-a-software-engineer' => 'pages#tlase'
  get '/newsletter/learn-to-code-in-60-days' => 'pages#sixty_day'

  devise_for :admins, :controllers => { registrations: 'registrations' }
  get 'admins/dashboard' => 'admins#dashboard'

  scope format: false do
    get '/*date/*title', to: 'blog_posts#show', date: %r[\d{4}/\d{2}/\d{2}], as: 'post'
  end

  get '/sitemap.xml', :to => 'sitemaps#index', :defaults => {:format => 'xml'}

  get '/pages/thank_you'
  get '/coding_foundations/thank_you' => "open_prework#thank_you"
  get '/pages/webinar_thank_you'
  get '/pages/tlase_thank_you'
  get '/pages/contacts_thank_you', :as => :contacts_thank_you
  get "/tours/thank_you" => "tours#thank_you", :as => :tours_thank_you
  get "/pages/tours/thank_you" => "pages#tour_thank_you", :as => :pages_tours_thank_you
  get '/pages/scholarship_thank_you'
  get '/corporate_training' => 'corporate_training_messages#corporate_training', :as => :corporate_training
  get '/corporate_training_thank_you' => 'corporate_training_messages#thank_you', :as => :corporate_training_thank_you

  get '/privacy_policy' => 'pages#privacy_policy'

  get "/apply" => "subscribers#apply", :as => :new_application #new_application_path has been altered for split test
  get "/applications/new/:id" => "applications#new"

  get "/subscribers/download"
  get "/subscribers/career_pdf_download"

  post 'subscribers_application' => 'subscribers#create_from_started_application'
  post 'subscribers_curriculum' => 'subscribers#create_from_curriculum'
  post 'subscribers_teaching_book' => 'subscribers#create_from_teaching_book'
  post 'subscribers_tutorial' => 'subscribers#create_from_tutorial'
  post 'subscribers_footer' => 'subscribers#create_from_footer'
  post 'subscribers_webinar' => 'subscribers#create_from_webinar'
  post 'subscribers_tlase' => 'subscribers#create_from_tlase'
  post 'subscribers_sixty_day' => 'subscribers#create_from_sixty_day'
  post 'subscribers_blog' => 'subscribers#create_from_blog'
  post 'subscribers_career_pdf' => 'subscribers#create_from_career_pdf'
  post 'subscribers_tour' => 'subscribers#create_from_tour'
  post 'subscribers' => 'subscribers#create_from_tour'
  post 'subscribers_popup' => 'subscribers#create_from_popup'

  resources :blog_posts
  resources :blog_categories
  resources :applications
  resources :scholarships, only: [:new, :create]
  resources :lakewood_applications
  resources :statuses, only: [:edit, :update]
  resources :faqs
  resources :contacts
  resources :mini_courses
  resources :mini_course_applications
  resources :subscribers, :only => [:index]
  resources :capstones, only: [:index]
  resources :screencasts, only: [:index]
  resources :interviews
  resources :corporate_training_messages, only: [:index, :new, :create, :show]
  resources :tours
  resources :info_session_sign_ups
  resources :info_sessions

  get "/careers" => "job_openings#index", as: :careers

  get "/options/" => "interviews#interview_options"

  get "/videos/think-like-a-software-engineer" => 'videos#tlase_show'
  get "/videos/learn-to-code-in-60-days" => 'videos#sixty_day_show'

  get "/think-like-a-software-engineer/videos" => 'videos#tlase_index'
  post "/think-like-a-software-engineer/videos" => 'videos#tlase_create'
  get "/think-like-a-software-engineer/videos/new" => 'videos#tlase_new'
  get "/think-like-a-software-engineer/videos/:episode_id/edit" => 'videos#tlase_edit'
  patch "/think-like-a-software-engineer/videos/:episode_id" => 'videos#tlase_update'
  get "/think-like-a-software-engineer/videos/:episode_id" => 'videos#new_tlase_show'

  get "/tutorial/lessons" => "lessons#index"
  get "/tutorial/lessons/:title" => "lessons#show"

  get "/tutorial_submissions" => "tutorial_submissions#index"
  post "/tutorial_submissions" => "tutorial_submissions#create"
  patch "/tutorial_submissions/ajax" => "tutorial_submissions#ajax_update"

  get "/profiles" => "profiles#index"
  patch "/profiles/:id" => "profiles#update"
  post "/profiles" => "profiles#create"
  get "/profiles/:id" => "profiles#modal"

  get "/lakewood_profiles" => "lakewood_profiles#index"
  patch "/lakewood_profiles/:id" => "lakewood_profiles#update"
  post "/lakewood_profiles" => "lakewood_profiles#create"
  get "/lakewood_profiles/:id" => "lakewood_profiles#modal"

  get "/referrals" => "referrals#index", :as => :referrals
  get "/referrals/new" => "referrals#new", :as => :new_referral
  post "/referrals" => "referrals#create"
  get "/referrals/thank_you" => "referrals#thank_you"

  get "/coding-bootcamps/community-info" => "pages#communities_index"
  get "/coding-bootcamps/:location/community-info" => "pages#communities"
  get "/codecademy" => "pages#codecademy"
  get "/resources" => "pages#resources"

  get "/codenewbie" => 'pages#codenewbie'
  get "/code-newbie" => 'pages#codenewbie'
  get "/codenewbies" => 'pages#codenewbie'

  post "/social-media" => 'social_media#new_post'

  get "/coding-foundations" => "open_prework#index"
  get "/enroll/coding-foundations" => "open_prework#enroll_form"
  get "/coding-foundations/terms-of-service" => "open_prework#terms_of_service"
  post "/enroll/coding-foundations" => "open_prework#enroll"
  get "/coding-foundations/thank-you" => "open_prework#thank_you"
  get "/enroll/email" => "open_prework#email"

  get "/josh/appreciation/new" => "pages#josh_new"
  post "/josh/appreciation" => "pages#josh_create"
  get "/josh/appreciation" => "pages#josh_index"

end

app/models/corporate_training_message.rb
class CorporateTrainingMessage < ActiveRecord::Base
  has_and_belongs_to_many :field_of_interests, dependent: :destroy

  validates :company_name, :contact_first_name, :contact_last_name, :contact_title, :contact_email, :contact_phone, :team_size, :start_date, :training_city, :training_state, :address_1, :city, :state, presence: true
  validates :contact_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  # validates :contact_phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }

  def friendly_updated_at
    updated_at.strftime("%A, %d %b %Y %l:%M %p")
  end

  def friendly_start_date
    start_date.strftime("%b %d, %Y")
  end

  def full_name
    "#{contact_first_name} #{contact_last_name}"
  end

  def training_location
    "#{training_city}, #{training_state}"
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |application|
        csv << application.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/corporate_training_messages_controller.rb
class CorporateTrainingMessagesController < ApplicationController
  before_action :authenticate_admin!, except: [:new, :create, :corporate_training, :thank_you]
  before_action :authenticate_corporate_training_access, only: [:index, :show]
  invisible_captcha only: [:create], honeypot: :subtitle
  layout 'corporate_training_messages', except: [:corporate_training]

  def index
    @corporate_training_messages = CorporateTrainingMessage.all

    respond_to do |format|
      format.html
      format.csv { send_data @corporate_training_messages.to_csv }
    end
  end

  def new
    @corporate_training_message = CorporateTrainingMessage.new
    @field_of_interests = FieldOfInterest.all
  end

  def create
    @corporate_training_message = CorporateTrainingMessage.new(corporate_training_message_params)

    if @corporate_training_message.save
      AcltcMailer.corporate_training_message(@corporate_training_message).deliver_now
      AcltcMailer.corporate_training_message_reply(@corporate_training_message).deliver_now
      redirect_to corporate_training_thank_you_path
    else
      render :new
    end
  end

  def show
    @corporate_training_message = CorporateTrainingMessage.find(params[:id])
  end

  def corporate_training
    render :layout => 'corporate_training_home'
  end

  def thank_you
  end

  private
  
  def corporate_training_message_params
    params.require(:corporate_training_message).permit(
      :company_name, 
      :address_1,
      :address_2,
      :city,
      :state,
      :contact_first_name,
      :contact_last_name, 
      :contact_title, 
      :contact_email, 
      :contact_phone, 
      :training_city, 
      :training_state,
      :team_size,
      :start_date,
      :message,
      field_of_interest_ids: []
    )
  end
end

app/helpers/corporate_training_messages_helper.rb
module CorporateTrainingMessagesHelper
end

app/views/corporate_training_messages/corporate_training.html.erb
<div id="corporate-training-home-page">
  <div class="marquee corporate-training-background-image">
    <div id = "marquee" class="container">
      <div class="row">
        <div class="marquee-content clearfix">
          <div class="col-md-12">
            <img class="logo corporate-logo" src="<%= asset_path 'corporate_training_logo_header.png'%>">
          </div>
          <div class="col-md-12">
            <h3>Top-notch training for teams in full-stack web development</h3><br>
          </div>
          <p>Our corporate training program certifies your team as full-stack software developers. With a customized curriculum, our experienced educators coach trainees at any level of technical expertise in the skills that apply to your organization’s technology and software, driving efficiency and increasing revenue.</p><br />
          <div class="row">
            <div class="col-md-12">
              <%= link_to "Schedule Consultation", new_corporate_training_message_path, class: "btn", id: "top-application-button" %>
            </div>
            <br>
          </div>
        </div> <!-- Ends row for Corporate Training Intro" -->
      </div>
    </div>
  </div>

  <div class="our-program-wrapper page-wrapper">
    <div class="home-section">
      <div class="row">
        <div class="col-md-12 our-program">
        <!--   <div class="section-header">
            <h2 class = "acltc-penguin-logo-small">Program</h2>
          </div> -->
          <div class="phase">
            <div class="phase-block col-6-xs phase-border">
              <div class="phase-point-right"></div>
                <h2>Training Philosophy</h2><br>
                <p class="text-left">At Anyone Can Learn To Code, we are educators who understand how people learn. We bring our classroom to your company, bridging the gap between traditional education and your company’s organizational and revenue goals. Our training produces full-stack developers not only with a broad set of coding skills, but who can apply their knowledge to your technology as well as your clients’ own.</p>
            </div>
            <div class="phase-block col-6-md">
              <img class="philosophy-icon" src="<%= asset_path 'corporate_training_karen.png'%>">
            </div>
          </div>
          <div class="phase">
            <div class="phase-block col-6-md phase-border">
              <div class="phase-point-right"></div>
                <h2>Customizable Program</h2><br>
                <p class="text-left">The ACLTC Corporate Training program is fully customizable based on your team’s needs and goals. We collaborate with you to design an ideal curriculum focused on your organization’s production and revenue goals. We’ll work together to choose the technologies and frameworks taught, a program schedule (including length in weeks and hours in class per day), and deliverables.</p>
            </div>
            <div class="phase-block col-6-md">
              <img class="philosophy-icon" src="<%= asset_path 'corporate_training_ny_trevor.png'%>">
            </div>
          </div>
          <div class="phase">
            <div class="phase-block col-6-md phase-border">
              <div class="phase-point-right"></div>
                <h2>Outcomes</h2><br>
                <p class="text-left">After completing our training program, your team of developers will be certified as full-stack developers. They will be:</p>
                <ul>
                  <li class="text-left outcome-text">Proficient in all technologies and frameworks taught throughout the course</li>
                  <li class="text-left outcome-text">Familiar with industry best practices, strategies, and methodologies</li>
                  <li class="text-left outcome-text">Able to work efficiently and effectively together to develop excellent products for your organization and for your clients</li>
                </ul>
            </div>
            <div class="phase-block col-6-md">
              <img class="philosophy-icon" src="<%= asset_path 'corporate_training_terry.png'%>">
            </div>
          </div>
        </div> <!-- col-12 -->
      </div> <!-- /row -->
      <div class="row">
        <div class="col-12-md centered">
          <div class="col-md-12 centered">
            <%= link_to "Schedule Consultation", new_corporate_training_message_path, class: "btn", id: "top-application-button" %>
          </div>
        </div>
      </div>
    </div> <!-- home-section -->
  </div> <!-- our-program-wrapper close corporate training description-->

  <div class="curriculum-wrapper page-wrapper">
    <div class="home-section">
      <div class="row">
        <div class="col-md-12 skills">
          <div class="section-header">
            <h2 class = "acltc-new-logo-circular">Curriculum & Instruction</h2>
            <p>Below are the technologies, frameworks, and skills in which Anyone Can Learn To Code trains web developers. Your team’s curriculum is fully customizable, leaving your programmers proficient in any of the following:</p>
          </div>
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'ruby_icon.png'%>">
                <h3>Ruby</h3>
              </div> 
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'rails_icon.png'%>">
                <h3>Rails</h3>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'node_js_icon.png'%>">
                <h3>NodeJS <br />&nbsp; </h3>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'python_icon.png'%>">
                <h3>Python</h3>
              </div>
            </div>
          </div> <!-- ends 1st row -->
          <br>
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'angular_icon.png'%>">
                <h3>AngularJS</h3>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'express_icon.png'%>">
                <h3>Express</h3>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'javascript_icon.png'%>">
                <h3>JavaScript</h3>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <%= image_tag "jquery_icon.png", class: "curriculum-icon" %>
                <h3>jQuery</h3>
              </div>
            </div>
          </div> <!--- ends 2nd row -->
          <br>
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'html_icon.png'%>">
                <h3>HTML</h3>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'css_icon.png'%>">
                <h3>CSS</h3>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'mongodb_icon.png'%>"><br />
                <h3>MongoDB</h3>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="skill gray-skill-wrapper border-bottom-yellow">
                <img class="curriculum-icon" src="<%= asset_path 'git_icon.png'%>">
                <h3>Git</h3>
              </div>
            </div>
          </div>
          <br /><br>
          <p class ="after-word">Educational best practices and pedagogy remain a strong focus throughout the ACLTC Corporate Training program. Throughout all training modules, our educator-instructors implement a philosophy that includes Understanding by Design (UbD), Guided Practice, Peer Review, Analysis & Evaluation, Collaboration, and Group & Independent Work.</p><br />
          <br />          
        </div> <!-- col-12 -->
      </div> <!-- row -->
    </div> <!-- home section -->
  </div><!-- curriculum wrapper close -->
<!--   <div class="locations-wrapper page-wrapper">
    <div class="home-section">
      <div class="section-header">
        <h2 class = "acltc-new-logo-circular">Curriculum Stats</h2>
      </div>
      <div class="row">
        <div class="corporate-charts">
          <h3 class="text-center">Programming Language Popularity on GitHub</h3><br>
          <div id="github-stats" style="height: 300px;"></div>
        </div>
      </div>
    </div>
  </div> -->
  <div class="testimonial-wrapper page-wrapper">
    <div class="home-section centered">
      <div class="row">
        <h2 class = "acltc-penguin-logo-small corporate-trainers">Trainers</h2>
        <div class="col-md-4 border-right">
          <img class="logo" src="<%= asset_path 'corporate_trainer_peter.png'%>">
          <div class="testimonial">
            <h3>Peter Jang</h3>
            <h4>Dean of Instruction & Chicago Lead Instructor</h4>
            <p>
              Peter Jang is the Dean of Instruction and a lead instructor at the Chicago location of Actualize, ACLTC’s coding school & apprenticeship program. He has worked at several startups, taught high school for six years, authored and maintained AvsP (an open-source video editor), and worked as a mechanical engineering consultant for a Fortune 500 company. He is also well-known in the Chicago Pilsen neighborhood karaoke circuit for his performances in both English and Spanish.
            </p>
          </div>
        </div>
        <div class="col-md-4 border-right">
          <img class="logo" src="<%= asset_path 'corporate_trainer_mark.png'%>">
          <div class="testimonial">
            <h3>Mark Richardson</h3>
            <h4>San Francisco Lead Instructor</h4>
            <p>
              For more than half a decade, Mark taught English as a Second Language to adults in Japan, Spain, Russia, Korea, and Chile. After returning to the States, he began his career as a full-stack developer, working for a startup in Chicago. It wasn’t long before he got the itch to combine his two loves: teaching and web development. Mark is currently the Lead Instructor in San Francisco for Actualize, ACLTC’s coding school & apprenticeship program.
            </p>
          </div>
        </div>
        <div class="col-md-4">
          <img class="logo" src="<%= asset_path 'corporate_trainer_josh.png'%>">
          <div class="testimonial">
            <h3>Josh Nixon</h3>
            <h4>Chicago Lead Instructor</h4>
            <p>
              Before making the switch to a serious coding career in 2013, Josh spent a little over a decade working as an entertainer in Los Angeles, starting with a BA in Theatre Arts. During that time he facilitated creativity workshops, taught improv classes, and coached privately for public speaking. After many years of playing with code Josh made it a career, working as a private consultant for phone and web applications. Before joining the Actualize program as a Lead Instructor, Josh was the Lead Rails Instructor at Code Chicago. He also has an affinity for robots.
            </p>
          </div>
        </div>
        <div class="col-md-12 centered">
          <%= link_to "Schedule Consultation", new_corporate_training_message_path, class: "btn", id: "top-application-button" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/corporate_training_messages/index.html.erb
<%= render "/layouts/page_title", page_title: "Corporate Training Messages", page_subtitle: "" %>
<section id="content">
  <div class="content-wrap">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <%= link_to "Download Corporate Messages CSV", corporate_training_messages_path(format: "csv"), :class => 'button btn-secondary csv-button'  %>
        <table class="table table-striped">
          <tr>
            <th>Company Name</th>
            <th>Message Sent</th> 
            <th>Email</th>
            <th>Start Date</th>
            <th>Training Location</th>
          </tr>
          <% @corporate_training_messages.each do |corporate_training_message| %>
          <tr>
            <td><%= link_to corporate_training_message.company_name, corporate_training_message_path(corporate_training_message) %></td>
            <td><%= corporate_training_message.friendly_updated_at %></td> 
            <td><%= corporate_training_message.contact_email %></td>
            <td><%= corporate_training_message.friendly_start_date %></td>
            <td><%= corporate_training_message.training_location %></td>
          </tr>
          <% end %>
        </table>

      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</section>

app/views/corporate_training_messages/show.html.erb
<%= render "/layouts/page_title", page_title: "Corporate Training Message", page_subtitle: "" %>
<section id="content">
  <div class="content-wrap">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
      <%= link_to "Back to Index", corporate_training_messages_path %>
        <table class="table table-striped">
          <tr>
            <th>Company Name:</th>
            <th><%= @corporate_training_message.company_name %></th> 
          </tr>
          <tr>
            <th>Address One:</th>
            <th><%= @corporate_training_message.address_1 %></th> 
          </tr>
          <tr>
            <th>Address Two:</th>
            <th><%= @corporate_training_message.address_2 %></th> 
          </tr>
          <tr>
            <th>City:</th>
            <th><%= @corporate_training_message.city %></th> 
          </tr>
          <tr>
            <th>State:</th>
            <th><%= @corporate_training_message.state %></th> 
          </tr>
          <tr>
            <th>Company Contact:</th>
            <th><%= @corporate_training_message.full_name %></th> 
          </tr>
          <tr>
            <th>Company Contact Title:</th>
            <th><%= @corporate_training_message.contact_title %></th> 
          </tr>
          <tr>
            <th>Email:</th>
            <th><%= @corporate_training_message.contact_email %></th> 
          </tr>
          <tr>
            <th>Phone:</th>
            <th><%= @corporate_training_message.contact_phone %></th> 
          </tr>
          <tr>
            <th>Team Size:</th>
            <th><%= @corporate_training_message.team_size %></th> 
          </tr>
          <tr>
            <th>Start Date:</th>
            <th><%= @corporate_training_message.friendly_start_date %></th> 
          </tr>
          <tr>
            <th>Training Location:</th>
            <th><%= @corporate_training_message.training_location %></th> 
          </tr>
          <tr>
            <th>Languages and Frameworks:</th>
            <% interests = "" %>
            <% @corporate_training_message.field_of_interests.each do |interest| %>
              <% interests = interests + interest.name + " " %>
            <% end %>
            <td><%= interests %></td>
          </tr>
          <tr>
            <th>Message:</th>
            <th><%= @corporate_training_message.message %></th> 
          </tr>          
          <tr>
            <th>Message Sent:</th>
            <th><%= @corporate_training_message.friendly_updated_at %></th> 
          </tr>
        </table>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</section>

app/views/corporate_training_messages/thank_you.html.erb
<div class="jumbotron jumbo-thanks">
  <h1>Thanks for reaching out to Anyone Can Learn To Code!</h1>
  <h2>We received your information and your Training Consultant will reach out to you shortly.</h2>
</div>
<!-- Google Code for Send A Message Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
  var google_conversion_id = 926873760;
  var google_conversion_language = "en";
  var google_conversion_format = "3";
  var google_conversion_color = "ffffff";
  var google_conversion_label = "x1LvCKHw8mQQoPH7uQM";
  var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
  <div style="display:inline;">
  <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/926873760/?label=x1LvCKHw8mQQoPH7uQM&amp;guid=ON&amp;script=0"/>
  </div>
</noscript>